### ISSUE TITLE
Special Characters and Bash

### ISSUE THREAD

**Issue by GIS-Nemo** [mikepound/pwned-search#1]
If you run the program as demonstrated at a Bash command, you could wind up with funky things happening if you have special characters in your password.

If your password is TheyreGreat!!!, and you run `python pwned.py TheyreGreat!!!`, Bash will interpret the double exclamation points as a call back to the last command run.

If your password is TheyreGreat!$, Bash will interpret the !$ as the last word of the last command run.

If your password is TheyreGreat!100, Bash will interpret the !100 as the hundredth command in your history.

To run the program properly, you'll have to put single quotes around your password if you have special characters in it.  Otherwise, the program would need to be rewritten to as for the password as input rather than a command-line argument.

And, TheyreGreat!!! is not found.

**Comment by mina86** [comment]
You don’t want to put passwords on command line anyway since they can be seen by other users with the help of `ps` and they may end up in your shell’s history file. https://github.com/mikepound/pwned-search/pull/2/commits/068f0832f795793ec2a4305a226bffaad40893a1 is what you want.

**Comment by StickyLophophora** [comment]
You should be able to use single quotes around the password, but like mina86 said, it's not the safest thing.

**Comment by jaimeteb** [comment]
However if you want to test your password but don't not want to store the command in history, put a single space at the beginning: " python pwned.py ..."

**Comment by mina86** [comment]
> However if you want to test your password but don't not  want to store the command in history, put a single space at the  beginning: " python pwned.py ..."

That’s not guaranteed to work and depends on shell’s configuration. Specifically, bash requires `ignorespace` being present in `HISTCONTROL` environment variable.

**Comment by mikepound** [comment]
The new merge allows you to redirect stdin, or enter commands within the script itself - hopefully this works for you.
