### ISSUE TITLE
Input degradation in C# version

### ISSUE THREAD

**Issue by 0xE1** [mikepound/pwned-search#19]
C# version uses ASCII encoding to read the input text, which is not in-line with Python version where utf-8 is used.

**Comment by mikepound** [comment]
I agree this could be improved. If I have a sec I'll try and do it, feel free to put a PR on for it.

**Comment by ghost** [comment]
I believe I fixed the issue. Just opened up a pull request.

**Comment by mikepound** [comment]
👍

**Comment by SparkDustJoe** [comment]
I opened a separate issue without reading this one... #24 my bad... If there's already a fix in the works, mine can be closed as well.
