### ISSUE TITLE
Encoding issue when generating SHA (c# code)

### ISSUE THREAD

**Issue by SparkDustJoe** [mikepound/pwned-search#24]
Example used 'correct horse battery staple'
Not found when:
byte[] data = sha.ComputeHash(Encoding.Unicode.GetBytes(plaintext));
CC8FA060AEE866AF1D5E829F5A10AFEDEE435577
Found when:
byte[] data = sha.ComputeHash(Encoding.ASCII.GetBytes(plaintext));
ABF7AAD6438836DBE526AA231ABDE2D0EEF74D42
'AD6438836DBE526AA231ABDE2D0EEF74D42:3'

Have not tested the Python, but considering that was the example in the ComputerPhile video I'm guessing that one was tested much more extensively.

**Comment by SparkDustJoe** [comment]
Second example, with ASCII encoding, 'Password1' found 111658 times, not found when Unicode.

**Comment by mikepound** [comment]
Thanks, I think the issue was raised by someone else in a code comment. The C# Unicode is UTF-16, which is incorrect. I didn't write the C# originally, it's an easy fix but I haven't had time yet!

**Comment by SparkDustJoe** [comment]
No worries, I figure most people have probably chosen the Python route anyways.

Incidentally the video on password managers, I'm trying to get some information out of RoboForm on how they use the Master Password for authentication/encryption/storage.  Their white paper is a little vague but in the interest of having good options out there I'm doing my due diligence research.  They claim 4000+ iterations of PBKDF2(SHA256) with a 32-byte (256-bit) salt, but they also store a user-generated Private Key on their servers (encrypted of course) for data-retrieval from other devices if you sign up for their family or professional plans.  They use the https://github.com/dropbox/zxcvbn library at least for their password integrity checks which is nice.  Just need better details....  

Thanks for putting this out there and for working so much with Sean. Greatly appreciated 👍

**Comment by mikepound** [comment]
This was kindly fixed in #33 I believe.
